name: Continuous Delivery Pipeline For Frontend

on:
  push:
    branches:
      - RELEASE
  workflow_dispatch:

jobs:
  ci-cd:
    name: Continuous Delivery for Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to RELEASE branch
        run: |
          git checkout RELEASE
          git pull origin RELEASE
        if: success()

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: success()

      - name: Build and Push Docker Image To HCR
        run: |
          docker build -t registry.heroku.com/${{ secrets.FRONTEND_IMAGE_NAME }}/${{ secrets.FRONTEND_IMAGE_TAG }} .
          docker push registry.heroku.com/${{ secrets.FRONTEND_IMAGE_NAME }}/${{ secrets.FRONTEND_IMAGE_TAG }}
        working-directory: ./app/client
        if: success()

      - name: Release the Container
        run: |
          heroku container:release ${{ secrets.FRONTEND_IMAGE_TAG }} --app ${{ secrets.FRONTEND_IMAGE_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        if: success()
