name: Continuous Delivery Pipeline For Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci-cd:
    name: Continuous Delivery for Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to main branch
        run: |
          git checkout main
          git pull origin main
        if: success()

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: success()

      - name: Azure Login
        env:
          AZURE_CLIENT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}
          AZURE_CLIENT_SECRET: ${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}
          AZURE_TENANT_ID: ${{ fromJSON(secrets.AZURE_CREDENTIALS).tenantId }}
        run: |
          az login --service-principal \
            -u "$AZURE_CLIENT_ID" \
            -p "$AZURE_CLIENT_SECRET" \
            --tenant "$AZURE_TENANT_ID" > /dev/null
        working-directory: ./app/client
        if: success()

      - name: Fetch and Remap Secrets from Azure Key Vault
        run: |
          touch .env
          for secret_id in $(az keyvault secret list --vault-name "${{ secrets.VAULT_NAME }}" --query "[].id" -o tsv); do
            secret_name=$(basename "$secret_id")
            secret_value=$(az keyvault secret show --id "$secret_id" --query value -o tsv)
            env_name=$(echo "$secret_name" | tr '-' '_' | tr '[:lower:]' '[:upper:]')
            echo "${env_name}='${secret_value}'" >> .env
          done
        working-directory: ./app/client
        if: success()

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}
        if: success()

      - name: Build and Push Docker Image To HCR
        run: |
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME_FRONTEND }}/${{ secrets.FRONTEND_IMAGE_TAG }} .
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME_FRONTEND }}/${{ secrets.FRONTEND_IMAGE_TAG }}
        working-directory: ./app/client
        if: success()

      - name: Release the Container
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release ${{ secrets.FRONTEND_IMAGE_TAG }} --app ${{ secrets.HEROKU_APP_NAME_FRONTEND }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        if: success()
