name: Branch Cut from RELEASE to main
on:
  workflow_dispatch:

jobs:
  branch_cut:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: RELEASE
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Configure Git
        run: |
          git config --global safe.directory $(pwd)
          git config --global user.email "branch-cut-bot@noreply.github.com"
          git config --global user.name "Branch Cut Bot"
          git config --global pull.rebase false
          git config --global core.longpaths true

      - name: Fetch all branches
        run: |
          git fetch --all
          
      - name: Handle main branch
        run: |
          if git show-ref --quiet refs/remotes/origin/main; then
            echo "main branch exists, checking out..."
            git checkout main
            git pull origin main
          else
            echo "Creating main branch from RELEASE"
            git checkout -b main
            git push --set-upstream origin main
          fi

      - name: Merge RELEASE into main
        run: |
          git config --list | grep user
          git merge origin/RELEASE --no-edit -m "🔄 Merge latest from RELEASE into main"
          git push origin main

      - name: Check merge status
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Successfully merged RELEASE into main"
          else
            echo "❌ Merge failed from RELEASE to main"
            exit 1
          fi